source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'MDMCoreData', :exclusive => true do
  pod "MDMCoreData", :path => "../"
end

target 'MDMCoreDataTests', :exclusive => true do
    pod "MDMCoreData", :path => "../"
end